# Generated by Django 5.1.3 on 2024-11-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_participants'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='registered_events',
            field=models.ManyToManyField(blank=True, related_name='participants_in_event', to='events.event'),
        ),
    ]
