# Generated by Django 5.1.3 on 2024-11-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='assigned_tasks',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='assigned_events',
            field=models.ManyToManyField(blank=True, null=True, to='users.event'),
        ),
    ]
