# Generated by Django 5.1.3 on 2024-11-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accept_registrations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
