# Generated by Django 5.1.3 on 2024-11-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_accept_registrations_event_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('WorkShop', 'WorkShop'), ('Competition', 'Competition'), ('Tech Talk', 'Tech Talk'), ('Gaming', 'Gaming'), ('Entertainment', 'Entertainment')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='loaction',
            field=models.CharField(blank=True, choices=[('Location1', 'Location1'), ('Location2', 'Location2'), ('Location3', 'Location3'), ('Location4', 'Location4'), ('Location5', 'Location5')], max_length=50, null=True),
        ),
    ]
