# Generated by Django 5.1.3 on 2024-11-22 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_capacity_event_category_event_fee_event_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='loaction',
            new_name='location',
        ),
    ]
